### ISSUE TITLE
errorhandling

### ISSUE THREAD

**Issue by StefanHoutzager** [denodrivers/postgres#176]
Clients using this lib have to catch errors. Maybe an interesting alternative, based on haskell's either monad:
https://dev.to/_gdelgado/type-safe-error-handling-in-typescript-1p4n 
There is a more to find on this subject on internet

**Comment by Soremwar** [comment]
Thanks @StefanHoutzager , I like this model, very Rust like!

However I also consider that such a system should be written in the core of JS in order to be correctly implemented, otherwise it will be prone to runtime errors that the system can't predict, thus losing any type of type error soundness

Respectfully closing
