### ISSUE TITLE
Update conn to not be generic. From recent (breaking) deno change

### ISSUE THREAD

**Issue by jzaki** [denodrivers/postgres#280]
# Error
In project deps.ts: `export { Client } from "https://deno.land/x/postgres@v0.11.1/mod.ts";`

Run or test with deno produces error...
```
TS2315 [ERROR]: Type 'Conn' is not generic.
  #conn!: Deno.Conn<Deno.NetAddr>;
          ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.11.1/connection/connection.ts:149:11
```

# Fix
https://github.com/denodrivers/postgres/blob/master/connection/connection.ts#L149
Removing <Deno.NetAddr> (on my local cached postgres) allowed this to work for me, but there might be more to it.

# Reference
"It might be breaking again now that Conn is not generic anymore (for 1.9.0 users)" - https://github.com/denoland/deno/pull/10255#issuecomment-822373722

**Comment by Soremwar** [comment]
So, this is an awful fix, but it's how things will go since I introduced a breaking change to adjust to their breaking change, and now that they rolled back the breaking change I'm the one with the broken library :upside_down_face: 

Deno 1.9.0 can use 0.11.0
Deno 1.8.x and lower, and Deno 1.9.1 can use 0.10.x and 0.11.2 (coming soon)
