### ISSUE TITLE
"no pg_hba.conf entry for host ... SSL off " error for heroku database

### ISSUE THREAD

**Issue by borsemayur2** [denodrivers/postgres#283]
`url=postgres://user:pass@host:port/db?sslmode=require`

```
Sending fatal alert BadCertificate
error: 
Uncaught (in promise) InvalidData: invalid certificate: UnknownIssuer
this.#conn = await Deno.startTls(this.#conn, { hostname });
```

**Comment by Soremwar** [comment]
This issue sadly, means that you won't be able to connect to Heroku using TLS

Deno validates all certificates used to start a connection, and if (and I inspect this is the case here), the certificate is self signed or signed by an untrusted entity it will be discarded

Closing as "won't fix" because this is something that has to be addressed by the Deno development team, more info here https://github.com/denoland/deno/issues/5931
