### ISSUE TITLE
Easy to be insecure by accident.

### ISSUE THREAD

**Issue by qm3ster** [denodrivers/postgres#357]
It seems trivial that someone, especially unfamiliar with tagged template strings might write
```ts
client.queryArray(`SELECT ID, NAME FROM PEOPLE WHERE ID = ${arg}`)
```
where they were supposed to write
```ts
client.queryArray`SELECT ID, NAME FROM PEOPLE WHERE ID = ${arg}`
```
causing the arguments not to be escaped.

Perhaps it would be better to error or at least warn when `query_template_or_config === "string"` but `args.length === 0`.
This means that all static statements can still be passed as
```ts
client.queryArray`SELECT ID, NAME FROM PEOPLE`
```
and dynamically-loaded argumentless statements as
```ts
client.queryArray([my_query]) 
```

**Comment by Soremwar** [comment]
Problem with this is that template strings without arguments are a valid statement you can execute (in fact one that I use widely across `deno-postgres` codebase)

This is a known problem when working with template strings, one that is extensively covered in the [docs](https://deno-postgres.com/#/?id=regarding-non-argument-parameters), however there is no practical solution that I know of to solve this since this is a feature that relies in behavior already defined by JavaScript, not something that can be controlled on the library side

I'm gonna close this, but I'm open to discussion if you find a way to deal with the issues I expressed above

**Comment by Soremwar** [comment]
This is pre 1.0. We don't deprecate things here, we just remove them :laughing:

The following is a request that people often get wrong cause they don't understand how the template string system works, nevertheless is a very common one

```ts
await client.queryArray(`SELECT * FROM ${TABLE_NAME}`);
// Also
await client.queryArray(`SELECT ${fields.join(", ")} FROM MY_TABLE`);
```

Writing this is with the syntax A would break this query because qualifiers and keywords can't be provided as an argument in a prepared statement. The alternative here (passing them as an array) could prove problematic if they provide more items in the array, since it would assume we are dealing with a template string and attempt replacement of arguments (this wouldn't do much damage now, but it will once named parameters are implemented). There is no way to prevent this

**Comment by qm3ster** [comment]
```ts
// You mean if they did
await client.queryArray([`SELECT * FROM ${TABLE_NAME}`, arg0]);
// instead of
await client.queryArray([`SELECT * FROM ${TABLE_NAME}`], arg0);
// ?
// I see how that's a possible mistake to make.
// But after all, as soon as there's an argument, they can just write
await client.queryArray(`SELECT * FROM ${TABLE_NAME}`, arg0);
// already
```
I understand if this is too high friction, but my concern was the following scenario:
1. there's a parametrized tagged template call
1. it works
1. there's a refactor where it's put in parentheses (randomly, or for example replaced with a ternary/map)
1. it still works, no one suspects a thing
1. hax

Where can I read about what is planned for named parameters?

**Comment by Soremwar** [comment]
```ts
await client.queryArray([`SELECT * FROM ${TABLE_NAME}`, arg0]);
// instead of
await client.queryArray([`SELECT * FROM ${TABLE_NAME}`], arg0);
```
No, the second one would do nothing. What I mean is that the first one would either throw because no placeholders are found or replace something that looks like a placeholder

> it still works, no one suspects a thing
Pretty much

> Where can I read about what is planned for named parameters?
https://github.com/denodrivers/postgres/issues/223

I haven't settled on a syntax yet, and I'm worried we might handicap ourselves here

**Comment by dylanpyle** [comment]
I know this is an ancient thread, but +1 that this syntax seems pretty security-error-prone. Even reading the docs carefully it's hard to distinguish ``queryArray(`...`` from ``queryArray`...`` without a very close eye. I ended up writing a super gnarly pcregrep script to catch these cases locally.
