### ISSUE TITLE
invalid peer certificate: UnsupportedCertVersion

### ISSUE THREAD

**Issue by dragonwocky** [denodrivers/postgres#376]
I'm not entirely sure where the fault here lies, but I'm having problems connecting to a database over TLS with deno-postgres.

I've put together this code to connect to the database based off the example in the docs (https://deno-postgres.com/#/?id=ssltls-connection):

```js
const cert = await Deno.readTextFile(
    new URL("./postgres.crt", import.meta.url),
  ),
  config = {
    user: "postgres",
    password: Deno.env.get("POSTGRES_PWD"),
    hostname: Deno.env.get("POSTGRES_HOST"),
    port: "6543",
    database: "postgres",
    tls: { caCertificates: [cert] },
  },
  pool = new postgres.Pool(config, 3, true);
```

The `postgres.crt` file is an SSL certificate downloaded from within the database's Supabase dashboard:

![image](https://user-images.githubusercontent.com/16874139/151965693-0b2f7e92-9385-4d2d-adab-8e3b6353d73f.png)

When I run the script, I get this error:

```
Sending fatal alert BadCertificate
TLS connection failed with message: invalid peer certificate contents: invalid peer certificate: UnsupportedCertVersion
Defaulting to non-encrypted connection
```

This is happening both when I run the script locally and on Deno Deploy.

The only other reference to this error message I could find was https://github.com/denoland/deno/issues/13350, so it may be related.

Thanks.

Edit: I get the same error both with and without including `tls: { caCertificates: [cert] }` in the config on Deno v1.18.1. If I downgrade to Deno v1.15.0 to test I get the following error (again both with and without adding the cert to the config):

```
Sending fatal alert DecodeError
TLS connection failed with message: invalid certificate: BadDER
```

Everything else seems to work, i.e. I can perform database operations successfully, but the TLS connection is failing.

**Comment by Soremwar** [comment]
Deno is extremely strict regarding TLS connections, if your certificate

To skip this, you can run Deno with the --unsafely-ignore-certificate-errors flag( https://deno.com/blog/v1.13#disable-tls-)verification

This will allow you to run TLS with non-compliant certificates (even though you really shouldn't)

The fault relies on your database providers, and I hope this problem gets solved eventually as there is quite a lot with broken certificates running around (AFAIK, only Amazon and Azure provide actual valid certificates for their hosting)

**Comment by dragonwocky** [comment]
I see. Is there any way to whitelist that specific certificate? (That's what I had understood the point of the `tls: { caCertificates: [cert] }` to be.)
I would rather not completely disable certificate checking.

**Comment by Soremwar** [comment]
The point of `caCertificates` is to add a certificate authority to your certificate store. This works if your certificate is self signed, because it tells Deno that the authority for that certificate is indeed trusted

The problem with your certificate is a different one however (`UnsupportedCertVersion`) so Deno can't add it to the list of trusted authorities

**Comment by BrunoBernardino** [comment]
Just an update here, I've been talking with Supabase to get this fixed, and they fixed it today! Here's the final message from one of their engineers:

> I have patched the SSL cert to return the SAN now. Deno shouldn't complain about the certs.

And I can confirm I'm no longer hitting that, and didn't have to replace the certificates.

**Comment by h4l** [comment]
Despite @BrunoBernardino's success, I've been trying to use a Supabase DB with Deno via this library and am getting the same error as @dragonwocky . I've just been investigating what's wrong and I believe I've got to the bottom of it. The CA cert Supabase provide is fine. All the certificates they use in the cert chain are valid, the problem is that the first certificate in their chain is a version 1 cert, but rusttls (used by Deno and therefore this library) doesn't support anything but X509 Version 3 certificates, because the webpki library rusttls uses to parse X509 certs [only supports V3](https://github.com/briansmith/webpki/blob/17d9189981a618120fd8217a913828e7418e2484/src/cert.rs#L132).

You can verify this by using openssl s_client to establish a TLS connection and view information on it, such as the certificates used by the server:

```
$ echo '' | openssl s_client -starttls postgres -connect db.YOURDB.supabase.co:5432 -showcerts -CAfile supabase_ca.pem
```

That will establish a connection to your DB, you should see a line saying `Verification: OK` near the end, and it'll print out the PEM form of the certificate chain. For me, the first certificate is a V1 (use `openssl x509 -in supabase.pem -text` to view the cert).

I've got a support ticket open with supabase at the minute, hopefully they can use V3 certificates for their DBs instead.

**Comment by BrunoBernardino** [comment]
@h4l I haven't created any new Supabase projects recently, but one thing that happened since that I didn't mention here was that I had to open a support ticket and request they fix the certificates for all of my existing projects as well (not just the specific one I made the initial request for), so it seems like a manual thing they do. I did expect them to do it for _new_ projects automatically, though, but maybe that's not a good assumption.

**Comment by h4l** [comment]
Interesting, thanks @BrunoBernardino . The support person I'm talking to also said they may need to upgrade my DB to use the latest certs, so that sounds like the same situation as you.

**Comment by h4l** [comment]
I heard back from Supabase a few days ago, they've given my DB a V3 cert which fixed the issue. They say that all new databases will have the V3 certs by default, and older DBs will be gradually updated over time.

**Comment by farsightsoftware** [comment]
@h4l -

>  They say that all new databases will have the V3 certs by default...

Just FYI, sadly that doesn't appear to be the case, as I'm getting this error with a DB I created in February. :-|

**Comment by h4l** [comment]
Hmm, that's disappointing to hear @farsightsoftware! I don't understand this, especially as SupaBase are using Deno themselves for their Edge Functions product. How can they provide a service that's not able to securely connect to their own DBs? Perhaps they expect everyone to use the HTTP REST API to interact with the db.
